FIRST_NUMBER = 15
SECOND_NUMBER = 26
THIRD_NUMBER = 10

SUMMA = 0
SUBTRACTION = 0
MULTIPLICATION = 0
DIVISION = 0


SUMMA = sum(FIRST_NUMBER, SECOND_NUMBER, THIRD_NUMBER)
SUBTRACTION = FIRST_NUMBER - SECOND_NUMBER - THIRD_NUMBER
MULTIPLICATION = FIRST_NUMBER * SECOND_NUMBER * THIRD_NUMBER
DIVISION = FIRST_NUMBER / SECOND_NUMBER / THIRD_NUMBER

print(SUMMA)
print(SUBTRACTION)
print(MULTIPLICATION)
print(DIVISION)